# Generated by Django 4.2.1 on 2023-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('duration', models.PositiveSmallIntegerField(default=1)),
                ('level_of_hardness', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price_of_accommodation', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='images')),
                ('equipment', models.FileField(upload_to='equipments')),
                ('water', models.CharField(max_length=320)),
            ],
        ),
    ]
