# Generated by Django 4.2.1 on 2023-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0003_alter_routes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='name',
            field=models.CharField(default='route-name-default', max_length=320),
        ),
    ]
