# Generated by Django 4.2.1 on 2023-06-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0004_alter_routes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routes',
            name='level_of_hardness',
            field=models.CharField(choices=[('Лёгкий', 'Лёгкий'), ('Средний', 'Средний'), ('Сложный', 'Сложный'), ('Выживание', 'Выживание')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routes',
            name='name',
            field=models.CharField(default='generated-route', max_length=320),
        ),
    ]
