# Generated by Django 4.2.1 on 2023-06-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='level_of_hardness',
            field=models.CharField(choices=[('1', 'Лёгкий'), ('2', 'Средний'), ('3', 'Сложный'), ('4', 'Выживание')], max_length=20),
        ),
    ]
