# Generated by Django 5.0.4 on 2024-04-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0006_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generated-route', max_length=320)),
                ('duration', models.PositiveSmallIntegerField()),
                ('level_of_hardness', models.CharField(choices=[('Лёгкий', 'Лёгкий'), ('Средний', 'Средний'), ('Сложный', 'Сложный'), ('Выживание', 'Выживание')], max_length=20)),
                ('description', models.TextField()),
                ('price_of_accommodation', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='images')),
                ('equipment', models.FileField(upload_to='equipments')),
                ('water', models.CharField(max_length=320)),
                ('first', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
        migrations.AddField(
            model_name='routepoint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naturetrail.point'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naturetrail.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='points',
            field=models.ManyToManyField(through='naturetrail.RoutePoint', to='naturetrail.point'),
        ),
    ]
