# Generated by Django 5.0.4 on 2024-05-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0008_remove_route_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='route',
            name='picture',
        ),
    ]
