# Generated by Django 5.0.4 on 2024-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0009_remove_route_equipment_remove_route_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='equipment',
            field=models.FileField(null=True, upload_to='equipments'),
        ),
        migrations.AddField(
            model_name='route',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(default='generated-point', max_length=320),
        ),
    ]
