# Generated by Django 5.0.4 on 2024-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0010_route_equipment_route_picture_alter_point_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='order',
            field=models.PositiveSmallIntegerField(default=99),
            preserve_default=False,
        ),
    ]
