# Generated by Django 5.0.4 on 2024-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturetrail', '0011_point_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='closest_accomodation',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
